package com.tuinventario.api.report;

import com.tuinventario.api.domain.enums.ItemStatus;
import com.tuinventario.api.domain.enums.LoanStatus;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

final class ReportLocalization {

    private final String language;

    private ReportLocalization(String language) {
        this.language = language;
    }

    static ReportLocalization from(Locale locale) {
        if (locale == null) {
            return new ReportLocalization("es");
        }
        return switch (locale.getLanguage()) {
            case "en" -> new ReportLocalization("en");
            case "pt" -> new ReportLocalization("pt");
            default -> new ReportLocalization("es");
        };
    }

    String inventoryTitle(boolean adminView) {
        return switch (language) {
            case "en" -> adminView ? "Administrative inventory" : "Operational inventory";
            case "pt" -> adminView ? "Inventario administrativo" : "Inventario operacional";
            default -> adminView ? "Inventario administrativo" : "Inventario operativo";
        };
    }

    String loansTitle() {
        return switch (language) {
            case "en" -> "Loans";
            case "pt" -> "Emprestimos";
            default -> "Prestamos";
        };
    }

    String inventoryCsvFile(boolean adminView) {
        return switch (language) {
            case "en" -> adminView ? "inventory-admin.csv" : "inventory-operational.csv";
            case "pt" -> adminView ? "inventario-administrativo.csv" : "inventario-operacional.csv";
            default -> adminView ? "inventario-administrativo.csv" : "inventario-operativo.csv";
        };
    }

    String inventoryPdfFile(boolean adminView) {
        return switch (language) {
            case "en" -> adminView ? "inventory-admin.pdf" : "inventory-operational.pdf";
            case "pt" -> adminView ? "inventario-administrativo.pdf" : "inventario-operacional.pdf";
            default -> adminView ? "inventario-administrativo.pdf" : "inventario-operativo.pdf";
        };
    }

    String loansCsvFile() {
        return switch (language) {
            case "en" -> "loans.csv";
            case "pt" -> "emprestimos.csv";
            default -> "prestamos.csv";
        };
    }

    String reportLabel() {
        return switch (language) {
            case "en" -> "Report";
            case "pt" -> "Relatorio";
            default -> "Reporte";
        };
    }

    String generatedByLabel() {
        return switch (language) {
            case "en" -> "Generated by";
            case "pt" -> "Gerado por";
            default -> "Generado por";
        };
    }

    String generatedAtLabel() {
        return switch (language) {
            case "en" -> "Date";
            case "pt" -> "Data";
            default -> "Fecha";
        };
    }

    String scopeLabel() {
        return switch (language) {
            case "en" -> "Scope";
            case "pt" -> "Escopo";
            default -> "Alcance";
        };
    }

    String periodLabel() {
        return switch (language) {
            case "en" -> "Period";
            case "pt" -> "Periodo";
            default -> "Periodo";
        };
    }

    String wholeOrganization() {
        return switch (language) {
            case "en" -> "Entire organization";
            case "pt" -> "Toda a empresa";
            default -> "Toda la empresa";
        };
    }

    String locationFallback() {
        return switch (language) {
            case "en" -> "Location";
            case "pt" -> "Localizacao";
            default -> "Ubicacion";
        };
    }

    String invalidRangeMessage() {
        return switch (language) {
            case "en" -> "The start date cannot be later than the end date.";
            case "pt" -> "A data inicial nao pode ser maior que a data final.";
            default -> "La fecha inicial no puede ser mayor que la fecha final.";
        };
    }

    String pdfGenerationErrorMessage() {
        return switch (language) {
            case "en" -> "The PDF could not be generated.";
            case "pt" -> "Nao foi possivel gerar o PDF.";
            default -> "No fue posible generar el PDF.";
        };
    }

    List<String> inventoryHeaders(boolean adminView) {
        return switch (language) {
            case "en" -> adminView
                    ? List.of("Location", "Item", "SKU", "Category", "Unit", "Status", "Total stock", "Available", "Reserved", "On loan", "Damaged", "Last movement")
                    : List.of("Item", "SKU", "Category", "Status", "Available", "On loan", "Damaged", "Location", "Last movement");
            case "pt" -> adminView
                    ? List.of("Localizacao", "Item", "SKU", "Categoria", "Unidade", "Status", "Estoque total", "Disponivel", "Reservado", "Emprestado", "Danificado", "Ultimo movimento")
                    : List.of("Item", "SKU", "Categoria", "Status", "Disponivel", "Emprestado", "Danificado", "Localizacao", "Ultimo movimento");
            default -> adminView
                    ? List.of("Sede", "Articulo", "SKU", "Categoria", "Unidad", "Estado", "Stock total", "Disponible", "Reservado", "Prestado", "Danado", "Ultimo movimiento")
                    : List.of("Articulo", "SKU", "Categoria", "Estado", "Disponible", "Prestado", "Danado", "Sede", "Ultimo movimiento");
        };
    }

    List<String> loanHeaders() {
        return switch (language) {
            case "en" -> List.of("Borrower", "Item", "Location", "Status", "Due date", "Delivery date", "Close date", "Notes");
            case "pt" -> List.of("Tomador", "Item", "Localizacao", "Status", "Data limite", "Data de entrega", "Data de encerramento", "Observacoes");
            default -> List.of("Prestatario", "Articulo", "Sede", "Estado", "Fecha de vencimiento", "Fecha de entrega", "Fecha de cierre", "Notas");
        };
    }

    String itemStatus(ItemStatus status) {
        return switch (language) {
            case "en" -> switch (status) {
                case AVAILABLE -> "Available";
                case RESERVED -> "Reserved";
                case ON_LOAN -> "On loan";
                case MAINTENANCE -> "Maintenance";
                case DAMAGED -> "Damaged";
                case LOST -> "Lost";
                case ARCHIVED -> "Archived";
            };
            case "pt" -> switch (status) {
                case AVAILABLE -> "Disponivel";
                case RESERVED -> "Reservado";
                case ON_LOAN -> "Emprestado";
                case MAINTENANCE -> "Manutencao";
                case DAMAGED -> "Danificado";
                case LOST -> "Perdido";
                case ARCHIVED -> "Arquivado";
            };
            default -> switch (status) {
                case AVAILABLE -> "Disponible";
                case RESERVED -> "Reservado";
                case ON_LOAN -> "En prestamo";
                case MAINTENANCE -> "Mantenimiento";
                case DAMAGED -> "Danado";
                case LOST -> "Perdido";
                case ARCHIVED -> "Archivado";
            };
        };
    }

    String loanStatus(LoanStatus status) {
        return switch (language) {
            case "en" -> switch (status) {
                case APPROVED -> "Approved";
                case DELIVERED -> "Delivered";
                case OVERDUE -> "Overdue";
                case RETURNED -> "Returned";
                case REJECTED -> "Rejected";
                case CANCELED -> "Canceled";
            };
            case "pt" -> switch (status) {
                case APPROVED -> "Aprovado";
                case DELIVERED -> "Entregue";
                case OVERDUE -> "Vencido";
                case RETURNED -> "Devolvido";
                case REJECTED -> "Rejeitado";
                case CANCELED -> "Cancelado";
            };
            default -> switch (status) {
                case APPROVED -> "Aprobado";
                case DELIVERED -> "Entregado";
                case OVERDUE -> "Vencido";
                case RETURNED -> "Devuelto";
                case REJECTED -> "Rechazado";
                case CANCELED -> "Cancelado";
            };
        };
    }

    String rangeLabel(LocalDate fromDate, LocalDate toDate) {
        if (fromDate == null && toDate == null) {
            return switch (language) {
                case "en" -> "All history";
                case "pt" -> "Todo o historico";
                default -> "Todo el historial";
            };
        }
        if (fromDate != null && toDate != null) {
            return formatLocalDate(fromDate) + rangeSeparator() + formatLocalDate(toDate);
        }
        if (fromDate != null) {
            return switch (language) {
                case "en" -> "From " + formatLocalDate(fromDate);
                case "pt" -> "Desde " + formatLocalDate(fromDate);
                default -> "Desde " + formatLocalDate(fromDate);
            };
        }
        return switch (language) {
            case "en" -> "Until " + formatLocalDate(toDate);
            case "pt" -> "Ate " + formatLocalDate(toDate);
            default -> "Hasta " + formatLocalDate(toDate);
        };
    }

    String formatInstant(Instant instant, String timezone) {
        if (instant == null) {
            return "";
        }
        return DateTimeFormatter.ofPattern(dateTimePattern(), locale())
                .withZone(ZoneId.of(timezone))
                .format(instant);
    }

    private String formatLocalDate(LocalDate date) {
        return date.format(DateTimeFormatter.ofPattern(datePattern(), locale()));
    }

    private String rangeSeparator() {
        return switch (language) {
            case "en" -> " to ";
            default -> " a ";
        };
    }

    private String datePattern() {
        return switch (language) {
            case "en" -> "MM/dd/yyyy";
            default -> "dd/MM/yyyy";
        };
    }

    private String dateTimePattern() {
        return switch (language) {
            case "en" -> "MM/dd/yyyy hh:mm a";
            default -> "dd/MM/yyyy HH:mm";
        };
    }

    private Locale locale() {
        return switch (language) {
            case "en" -> Locale.ENGLISH;
            case "pt" -> Locale.forLanguageTag("pt");
            default -> Locale.forLanguageTag("es");
        };
    }
}
